name: Run Node.js Script

on:
  schedule:
    - cron: '0 */6 * * *' # Runs every 6 hours. Change as needed.
  workflow_dispatch: # Allows manual triggering if needed.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # or the version you need

      - name: Install Node.js dependencies
        run: npm install
        working-directory: ./html-to-image

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Run script
        run: node convert-to-image.js
        working-directory: ./html-to-image
